### ISSUE TITLE
update gpm error

### ISSUE THREAD

**Issue by ZhuTango** [zmicro-design/plugin-ta#34]
ℹ [2022-09-22 10:46:49] gpm version found update, try to update it ...
npm ERR! code 1
npm ERR! path /Users/zhujianshan/.node/lib/node_modules/@cliz/gpm/node_modules/raw-socket
npm ERR! command failed
npm ERR! command sh /var/folders/f2/63qkf3_16pj5_8mzg8qv5r8c0000gn/T/install-09835bc6.sh
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | darwin | arm64
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/opt/data/plugins/nvm/versions/v16.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/opt/data/plugins/nvm/versions/v16.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/opt/data/plugins/nvm/versions/v16.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/opt/data/plugins/nvm/versions/v16.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:408:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:420:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/opt/data/plugins/nvm/versions/v16.17.0/bin/node" "/opt/data/plugins/nvm/versions/v16.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/zhujianshan/.node/lib/node_modules/@cliz/gpm/node_modules/raw-socket
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zhujianshan/.npm/_logs/2022-09-22T02_46_49_730Z-debug-0.log

**Comment by ZhuTango** [comment]
ℹ node: v16.17.0
ℹ npm: v8.15.0
ℹ yarn: v1.22.18
ℹ gpm: v1.4.1
ℹ nvm: v1.3.2 (a286fdef0 2022-09-02)
ℹ ta: v1.4.8 (4dbf316bb 2022-09-22)
ℹ zmicro: v1.21.22 (22b5202a4 2022-09-21)
ℹ os:
ℹ   release: macOS 12.6
ℹ   arch: arm64
ℹ   kernel: Darwin
ℹ   platform: darwin
ℹ   device: 10C64G - 1.0TB

**Comment by whatwewant** [comment]
related: https://github.com/nodejs/node-gyp/issues/2670

**Comment by whatwewant** [comment]
node-gyp find python logic: https://github.com/nodejs/node-gyp/blob/v9.0.0/lib/find-python.js
